// <auto-generated />
namespace CitrusDB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_IEntity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_IEntity));
        
        string IMigrationMetadata.Id
        {
            get { return "201811091837294_add_IEntity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
