// <auto-generated />
namespace CitrusDB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class changestandartCRUDtostoredprocedurelogic : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changestandartCRUDtostoredprocedurelogic));
        
        string IMigrationMetadata.Id
        {
            get { return "201811071744097_change standart CRUD to stored procedure logic"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
